[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = cHjvytptybC8ym/SC+eXZBbAVWthiH+7yzf+eNEAnkc=
Address = 10.2.0.2/32
DNS = 1.1.1.1, 8.8.8.8
MTU = 1280

[Peer]
# NL-FREE#238
PublicKey = bnzfUDrEjYNRXBwzVTZ7+Y3KQ+wInUNlXWfui88NIwg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.100.234.177:51820

PersistentKeepalive = 25